### PR TITLE
Fixes Compiling Issues On Linux

### PR DESCRIPTION
**Pull request by DeathKhan**
Added a vectorized image icon as per Linux standard as well as a .desktop entry. 
Renamed EditControls Binary to Vircon32EditControls to stop on compile name scheme error. 
Changed install directory to /opt/ as per Linux standard.

TODO: Add Vircon32EditControls vector image and .desktop entry

### CODE REVIEW

**Comment by vircon32** [comment]
Hi DeathKan, thank you for contributing. I don't have any experience with pull requests yet, and I'm certainly not an expert on CMake, so I will have to ask you some questions about your changes:

1) I'm not understanding why the name change of EditControls to Vircon32EditControls is necessary. Unfortunately this would mean other changes too (in the help texts, guides, etc) so I'm not sure it's worth it. Adding the Vircon32 also seems redundant when it is located within the same emulator folder.
2) If I'm not mistaken, on CMake you are supposed to choose your install directory by setting the appropriate variables before building, so I'm not sure that setting it directly on the CMake script is going to play nice with that.
3) Setting the program icon and data on Linux is fine, though I will replace your SVG icon with the one I used so that the logo is accurate.

**Comment by DeathKhan** [comment]
> Hi DeathKan, thank you for contributing. I don't have any experience with pull requests yet, and I'm certainly not an expert on CMake, so I will have to ask you some questions about your changes:
> 
>     1. I'm not understanding why the name change of EditControls to Vircon32EditControls is necessary. Unfortunately this would mean other changes too (in the help texts, guides, etc) so I'm not sure it's worth it. Adding the Vircon32 also seems redundant when it is located within the same emulator folder.
> 
>     2. If I'm not mistaken, on CMake you are supposed to choose your install directory by setting the appropriate variables before building, so I'm not sure that setting it directly on the CMake script is going to play nice with that.
> 
>     3. Setting the program icon and data on Linux is fine, though I will replace your SVG icon with the one I used so that the logo is accurate.
1. It is necessary because when building from the location of CMakeLists, which is standard, EditControls cannot be built as there is already a directory with that name. This can be fixed by modifying the binary name or the name of the source folder to something like 'EditControlsSource'

2. /opt/ is standard for a third party compiled application bundle, but CMake already has a default on Linux and its /usr/local, there is no harm in over riding this and the user can still specify with the -DCMAKE_INSTALL_PREFIX flag

3. Sounds good!

**Comment by DeathKhan** [comment]
I updated the SVG to be accurate to the original logo.

**Comment by vircon32** [comment]
Thank you, that SVG is indeed more accurate :)

I believe the build problem you were having with EditControls happens because you are trying to do an in-source build. This is usually not recommended, but in case someone done it this way I would prefer to leave the executable name as EditControls and change the name of the source folder, from EditControls to ControlsEditor.

**Comment by vircon32** [comment]
I see you already made a commit with those changes, thank you. I will be busy today, but tomorrow I will test the build with these changes, to make sure we didn't break anything, and I see nothing strange I will accept the merge.

**Comment by vircon32** [comment]
Hi DeathKan. I have been able to build and install this PR, in both Windows and Linux. However, under Ubuntu, I expected that after these changes the emulator executable whould show some change in icon or properties. Nothing seems different though. Is something else required for this?

**Comment by DeathKhan** [comment]
Running `sudo make install` after `cmake .` should make it available as an actual application in your applications list with an icon, be sure to git clone my repo.

**Comment by vircon32** [comment]
Yes, I am building from your PR code, not from main. I have now seen that the emulator is indeed appearing in the applications list (didn't know about that). However it still appears with the default icon (a grey gear in Ubuntu). I have tried with both sudo make install and cmake --install, the result is the same.

There is also another issue: the emulator is being installed at /opt/Vircon32, but it should actually be one level deeper: /opt/Vircon32/Emulator. This is because, if the user also installs the dev tools (or other possible future tools), all installs would be placed under a common folder /opt/Vircon32, and each tool would be in its own independent subfolder, keeping everything grouped and clean.

**Comment by DeathKhan** [comment]
Fixed icon and folder structure

**Comment by vircon32** [comment]
Thank you DeathKan! I will test the build later today

**Comment by vircon32** [comment]
Everything seems correct now and the program icon is displayed. I have merged your pull request. Thank you!

**Pull request merged**
